#!/usr/bin/ruby

require 'fileutils'

CURRENT_DIR = File.dirname(__FILE__)
TEMPLATE_HTML = File.read("#{CURRENT_DIR}/lib/template.html")

# Usage
if (ARGV.length != 2) || (ARGV[0] != 'new')
  puts 'Usage : reveal new <presentation_name>'
  puts 'Example : ./reveal new "Ruby on Rails tutorial"'
  exit(1)
end

# Fetch the presentation name
presentation_name = ARGV[1]

# Process the template
presentation_html = TEMPLATE_HTML.gsub(/\[presentation_name\]/, presentation_name)

# Create the file
presentation_file_name = presentation_name.dup.downcase.gsub(/[^a-z0-9\-_]+/i, '_')
target_path = "#{CURRENT_DIR}/#{presentation_file_name}.html"

File.open(target_path, 'wb') do |file|
  file.write presentation_html
end

# Create the folder for assets
FileUtils.mkdir "#{CURRENT_DIR}/#{presentation_file_name}"

# Print help for the next step
puts "Your presentation is ready at #{target_path}"